# Generated by Django 4.1.5 on 2023-01-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('category', 'position')},
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, upload_to='dishes/%Y-%m-%d'),
        ),
    ]
