# Generated by Django 4.1.5 on 2023-02-07 20:41

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_about_events_reservation_dish_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='our_photo/%Y-%m-%d')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.URLField(help_text='enter url of video'),
        ),
    ]
