# Generated by Django 4.1.5 on 2023-02-09 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_reservation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Error phone number', regex='^(\\d{3}[- .]?){2}\\d{4}$')]),
        ),
    ]
