# Generated by Django 4.1.5 on 2023-02-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_reservation_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='chefs/%Y-%m-%d')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('is_visible',),
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='why_us/%Y-%m-%d')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('is_visible',),
            },
        ),
    ]
