# Generated by Django 4.1.5 on 2023-02-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_chefs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyus',
            name='position',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
