# Generated by Django 4.1.5 on 2023-02-10 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_whyus_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.CharField(default=0, max_length=50, validators=[django.core.validators.RegexValidator(message='Error email', regex='[a-zA-Z0-9]*(-?\\.?[_a-zA-Z0-9])*@[a-zA-Z0-9]+(\\.[a-zA-Z0-9]+)*')]),
            preserve_default=False,
        ),
    ]
